#SELECT YEAR(B.SALES_DATE) AS YEAR, 
#		MONTH(B.SALES_DATE) AS MONTH,
#        A.GENDER AS GENDER, 
#        COUNT(DISTINCT A.USER_ID) AS USERS
#FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
#GROUP BY YEAR, MONTH, GENDER
#HAVING GENDER IS NOT NULL 
#ORDER BY YEAR, MONTH, GENDER


# SELECT
#     YEAR(OS.SALES_DATE) AS YEAR,
#     MONTH(OS.SALES_DATE) AS MONTH,
#     UI.GENDER AS GENDER,
#     # UI.USER_ID AS USERS
#     COUNT(DISTINCT(UI.USER_ID)) AS USERS
# FROM USER_INFO AS UI
# JOIN ONLINE_SALE AS OS
# ON UI.USER_ID = OS.USER_ID
# GROUP BY YEAR,MONTH,GENDER
# HAVING GENDER IS NOT NULL
# ORDER BY YEAR,MONTH,GENDER


SELECT YEAR(OS.SALES_DATE) AS YEAR,
        MONTH(OS.SALES_DATE) AS MONTH,
        UI.GENDER,
        COUNT(DISTINCT(UI.USER_ID)) AS 'USERS'

FROM ONLINE_SALE AS OS
JOIN USER_INFO AS UI
ON OS.USER_ID = UI.USER_ID
GROUP BY YEAR,MONTH,GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR,MONTH,GENDER
