# -- 코드를 입력하세요
# SELECT CAR.CAR_ID,CAR.CAR_TYPE,CAR.DAILY_FEE AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS CAR

# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
# ON CAR.CAR_ID = HISTORY.CAR_ID

# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
# ON CAR.CAR_TYPE = PLAN.CAR_TYPE

# WHERE ( CAR.CAR_TYPE = '세단' OR CAR.CAR_TYPE = 'SUV' )
# AND (DATE_FORMAT(START_DATE,'%Y-%m-%d') < '2022-11-01') 
# AND (DATE_FORMAT(END_DATE,'%Y-%m-%d') > '2022-11-30')
# AND (CAR.DAILY_FEE * PLAN.DISCOUNT_RATE)


-- 코드를 입력하세요
-- 할인률 따로 묶기
WITH DC AS (
SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE IN ("세단", "SUV") && DURATION_TYPE = "30일 이상"
)

SELECT C.CAR_ID, C.CAR_TYPE, TRUNCATE((C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100), 0) AS FEE FROM CAR_RENTAL_COMPANY_CAR C
JOIN DC D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_ID NOT IN (
SELECT DISTINCT C.CAR_ID FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE IN ("세단", "SUV") && H.START_DATE <= DATE("2022-11-30") && H.END_DATE >= DATE("2022-11-01")
) && C.CAR_TYPE IN ("세단", "SUV") && TRUNCATE((C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100), 0) >= 500000 && TRUNCATE((C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100), 0) < 2000000

ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC