-- 코드를 입력하세요
WITH Y AS (SELECT DISTINCT CART_ID,NAME
FROM CART_PRODUCTS
WHERE NAME LIKE 'Yogurt')

, M AS (SELECT DISTINCT CART_ID,NAME
FROM CART_PRODUCTS
WHERE NAME LIKE 'Milk')

# WITH M AS (SELECT DISTINCT CART_ID, NAME
# FROM CART_PRODUCTS
# WHERE NAME LIKE 'Milk')

# , Y AS (SELECT DISTINCT CART_ID, NAME
# FROM CART_PRODUCTS
# WHERE NAME LIKE 'Yogurt')

SELECT Y.CART_ID
FROM Y
JOIN M
ON Y.CART_ID = M.CART_ID
