-- 코드를 입력하세요
# SELECT UR.USER_ID, UR.NICKNAME,
# CONCAT(UR.CITY, ' ', UR.STREET_ADDRESS1, ' ', UR.STREET_ADDRESS2) AS '전체주소',
# CONCAT(LEFT(UR.TLNO,3), '-', MID(UR.TLNO,4,4),'-',RIGHT(UR.TLNO,4)) AS '전화번호'
# FROM USED_GOODS_BOARD AS BOARD
# JOIN USED_GOODS_USER AS UR
# ON BOARD.WRITER_ID = UR.USER_ID
# GROUP BY BOARD.WRITER_ID
# HAVING COUNT(*) >=3
# ORDER BY  UR.USER_ID DESC

# SELECT u.USER_ID, u.NICKNAME, 
#     CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) AS 전체주소,
#     CONCAT(LEFT(u.TLNO, 3), '-', MID(u.TLNO, 4, 4), '-', RIGHT(u.TLNO, 4)) AS 전화번호
# FROM USED_GOODS_BOARD b
# INNER JOIN USED_GOODS_USER u
# ON b.WRITER_ID = u.USER_ID
# GROUP BY u.USER_ID
# HAVING COUNT(*)>=3
# ORDER BY u.USER_ID DESC;


SELECT UR.USER_ID, UR.NICKNAME,
CONCAT(UR.CITY, ' ', UR.STREET_ADDRESS1, ' ', UR.STREET_ADDRESS2) AS '전체주소',
CONCAT(LEFT(UR.TLNO,3), '-', MID(UR.TLNO,4,4),'-',RIGHT(UR.TLNO,4)) AS '전화번호'
FROM USED_GOODS_BOARD AS BOARD
JOIN USED_GOODS_USER AS UR
ON BOARD.WRITER_ID = UR.USER_ID
GROUP BY BOARD.WRITER_ID
HAVING COUNT(*) >=3
ORDER BY  UR.USER_ID DESC