-- 코드를 입력하세요
# SELECT count(DISTINCT name) AS count 
# FROM animal_ins
# WHERE name IS NOT NULL




SELECT COUNT(DISTINCT name)  FROM animal_ins
WHERE name IS NOT NULL



# SELECT COUNT(DISTINCT NAME)
# FROM ANIMAL_INS
# WHERE NAME IS NOT NULL