-- 코드를 입력하세요
# SELECT END_DATE - START_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

# DATEDIFF(DATE1,DATE2) => 시간,분,초 등을 고려하지 않고 일 수의 차이를 알려줌
# HAVING 과 WHERE 의 차이 = GROUP 화 된 테이블에서 조건 설정, 원래 테이블에서의 조건설정



SELECT CAR_ID , ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE,START_DATE)+1) >= 7
ORDER BY AVERAGE_DURATION DESC , CAR_ID DESC

# SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
# ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC