-- 코드를 입력하세요
# SELECT HALF.FLAVOR
# FROM FIRST_HALF AS HALF
# JOIN (SELECT FLAVOR , SUM(TOTAL_ORDER) AS TOTAL_ORDER
# FROM JULY
# GROUP BY FLAVOR ) AS JULY
# ON HALF.FLAVOR = JULY.FLAVOR
# ORDER BY ( HALF.TOTAL_ORDER + JULY.TOTAL_ORDER ) DESC
# LIMIT 3


# SELECT HALF.FLAVOR
# FROM FIRST_HALF AS HALF
# JOIN (
#     SELECT FLAVOR , SUM(TOTAL_ORDER) AS TOTAL_ORDER
#     FROM JULY
#     GROUP BY FLAVOR
# ) AS JULY
# ON JULY.FLAVOR = HALF.FLAVOR
# ORDER BY (JULY.TOTAL_ORDER + HALF.TOTAL_ORDER ) DESC
# LIMIT 3


SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
JOIN (
    SELECT FLAVOR , SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS JULY
ON FH.FLAVOR = JULY.FLAVOR
ORDER BY (FH.TOTAL_ORDER + JULY.TOTAL_ORDER) DESC
LIMIT 3











