-- 코드를 입력하세요
# SELECT A.FLAVOR
# FROM FIRST_HALF AS A
# JOIN (
#     SELECT FLAVOR, sum(TOTAL_ORDER) AS TOTAL_ORDER
#     FROM JULY
#     GROUP BY FLAVOR
# ) AS B
# ON A.FLAVOR = B.FLAVOR
# ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
# LIMIT 3

SELECT HALF.FLAVOR
FROM FIRST_HALF AS HALF
JOIN (SELECT FLAVOR , SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR ) AS JULY
ON HALF.FLAVOR = JULY.FLAVOR
ORDER BY ( HALF.TOTAL_ORDER + JULY.TOTAL_ORDER ) DESC
LIMIT 3













