-- 코드를 입력하세요
# SELECT USER.USER_ID,USER.NICKNAME,SUM(PRICE) AS TOTAL_SALE
# FROM USED_GOODS_BOARD AS BOARD
# JOIN USED_GOODS_USER AS USER
# ON BOARD.WRITER_ID = USER.USER_ID
# WHERE BOARD.STATUS = 'DONE'
# GROUP BY USER.USER_ID
# HAVING TOTAL_SALE >= 700000
# ORDER BY TOTAL_SALE ASC














SELECT UU.USER_ID,UU.NICKNAME,SUM(UB.PRICE) AS TOTAL_SALE
FROM USED_GOODS_BOARD AS UB
JOIN USED_GOODS_USER AS UU
ON UB.WRITER_ID = UU.USER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALE >= 700000
ORDER BY TOTAL_SALE ASC