SELECT 
        MEMBER_NAME
        ,REVIEW_TEXT
        ,date_format(REVIEW_DATE,"%Y-%m-%d") as REVIEW_DATE
    FROM (
        SELECT 
            MEMBER_ID
            ,COUNT(MEMBER_ID)
            ,dense_rank() over(ORDER BY COUNT(MEMBER_ID) DESC) as ran
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(MEMBER_ID) DESC
    ) A NATURAL JOIN MEMBER_PROFILE JOIN REST_REVIEW USING (MEMBER_ID)
    WHERE A.ran =1
    ORDER BY REVIEW_DATE,REVIEW_TEXT;

# SELECT * , RANK() OVER(ORDER BY REVIEW_SCORE) AS 'USER_RANK'
# FROM REST_REVIEW


# SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, 
#         DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE

# FROM MEMBER_PROFILE AS MP
# JOIN (
#     SELECT * , RANK() OVER( ORDER BY COUNT(MEMBER_ID) DESC) AS 'USER_RANK'
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
# ) AS RR
# ON MP.MEMBER_ID = RR.MEMBER_ID
# WHERE RR.USER_RANK = 1
# ORDER BY RR.REVIEW_DATE ASC , RR.REVIEW_TEXT ASC


# SELECT MP.MEMBER_NAME,RR.REVIEW_TEXT,(
#     DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') 
# ) AS REVIEW_DATE
# FROM MEMBER_PROFILE AS MP
# JOIN (
#     SELECT *, RANK() OVER( ORDER BY COUNT(MEMBER_ID) DESC ) AS 'USER_RANK'
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
# ) AS RR
# ON MP.MEMBER_ID = RR.MEMBER_ID
# WHERE RR.USER_RANK = 1
# ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC









