-- 코드를 입력하세요
# SELECT A.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,sum(C.SALES*B.PRICE) AS TOTAL_SALES
# FROM AUTHOR AS A
# JOIN BOOK AS B
# ON A.AUTHOR_ID = B.AUTHOR_ID
# JOIN BOOK_SALES AS C
# ON B.BOOK_ID  = C.BOOK_ID
# WHERE C.SALES_DATE LIKE '2022-01%'
# GROUP BY 1,2,3
# ORDER BY AUTHOR_ID , CATEGORY DESC

# SELECT A.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY , SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
# FROM AUTHOR AS A
# JOIN BOOK AS B
# ON A.AUTHOR_ID = B.AUTHOR_ID
# JOIN BOOK_SALES AS BS
# ON B.BOOK_ID = BS.BOOK_ID
# WHERE BS.SALES_DATE LIKE '2022-01%'
# GROUP BY A.AUTHOR_ID, B.CATEGORY , A.AUTHOR_NAME
# ORDER BY AUTHOR_ID ASC , CATEGORY DESC

SELECT AU.AUTHOR_ID, AU.AUTHOR_NAME, BO.CATEGORY, SUM(BS.SALES * BO.PRICE) AS TOTAL_SALES
FROM AUTHOR AS AU
JOIN BOOK AS BO
ON AU.AUTHOR_ID = BO.AUTHOR_ID
JOIN BOOK_SALES AS BS
ON BO.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE "2022-01%"
GROUP BY AU.AUTHOR_ID,AU.AUTHOR_NAME,BO.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC


















