-- 코드를 입력하세요
# SELECT A.product_code AS 'PRODUCT_CODE', SUM(A.price * B.sales_amount) AS 'SALES'
# FROM PRODUCT AS A JOIN OFFLINE_SALE AS B
# ON A.product_id = B.product_id
# GROUP BY A.product_code
# ORDER BY  SALES DESC , PRODUCT_CODE


SELECT P.PRODUCT_CODE , SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P
JOIN OFFLINE_SALE AS OS
ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC , PRODUCT_CODE ASC