-- 코드를 입력하세요
# SELECT
#     CASE
#     WHEN PRODUCT_ID = 1 or PRODUCT_ID = 2 THEN 'A1'
#     WHEN PRODUCT_ID = 3 or PRODUCT_ID = 4 or PRODUCT_ID = 5 THEN 'C3'
#     WHEN PRODUCT_ID = 6 THEN 'K1'
#     END AS CATEGORY
#     ,PRODUCT_ID
# FROM PRODUCT


# SELECT B.CATEGORY , COUNT(CATEGORY) AS PRODUCTS
# FROM PRODUCT AS A
# JOIN (   
#     SELECT
#     CASE
#     WHEN PRODUCT_ID = 1 or PRODUCT_ID = 2 THEN 'A1'
#     WHEN PRODUCT_ID = 3 or PRODUCT_ID = 4 or PRODUCT_ID = 5 THEN 'C3'
#     WHEN PRODUCT_ID = 6 THEN 'K1'
#     END AS CATEGORY
#     ,PRODUCT_ID
#     FROM PRODUCT
# ) AS B
# ON B.CATEGORY IS NOT NULL
# GROUP BY B.CATEGORY

SELECT  SUBSTR(PRODUCT_CODE,1,2) AS CATEGORY
        , COUNT(*)
FROM  PRODUCT 
GROUP BY  SUBSTR(PRODUCT_CODE,1,2)