-- 코드를 입력하세요
# SELECT A.PRODUCT_ID, A.PRODUCT_NAME , SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
# FROM FOOD_PRODUCT AS A
# JOIN FOOD_ORDER AS B
# ON A.product_id = B.product_id
# WHERE B.produce_date like "2022-05%"
# GROUP BY A.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC , PRODUCT_ID



SELECT FP.PRODUCT_ID,FP.PRODUCT_NAME,SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN FOOD_ORDER AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE '2022-05%'
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
