# SELECT count(animal_id) AS count
# from animal_ins


# SELECT COUNT(ANIMAL_ID) AS 'count'
# FROM ANIMAL_INS


# SELECT COUNT(ANIMAL_ID) AS 'count'
# FROM ANIMAL_INS

SELECT COUNT(ANIMAL_ID) AS 'count'
FROM ANIMAL_INS