-- 코드를 입력하세요
# SELECT A.REST_ID,A.REST_NAME,A.FOOD_TYPE,A.FAVORITES,A.ADDRESS,
# ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
# FROM REST_INFO AS A
# JOIN REST_REVIEW AS B
# ON A.REST_ID = B.REST_ID
# GROUP BY A.REST_ID
# HAVING A.ADDRESS LIKE '서울%'
# ORDER BY SCORE DESC , A.FAVORITES DESC





SELECT RI.REST_ID,RI.REST_NAME,RI.FOOD_TYPE,RI.FAVORITES,RI.ADDRESS
,ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS RI
JOIN REST_REVIEW AS RR
ON RI.REST_ID = RR.REST_ID
GROUP BY RI.REST_ID
HAVING RI.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, RI.FAVORITES DESC